### ISSUE TITLE
rtrim not available on CRAN anymore

### ISSUE THREAD

**Issue by lionel68** [SNStatComp/rtrim#23]
Hullo,

it seems that rtrim is not on CRAN anymore, the command:

```
install.packages("rtrim")
````

does not work any more, do you have a temporary solution for this?

**Comment by RetoSchmucki** [comment]
@lionel68 

I'm maintainer or involved in the rtrim project and I don't know the reason why it has been removed from CRAN, but for a temporary solution you can still install **rtrim** from GitHub using **install_github()** from the **devtools** package or any other alternative to install from here.

`devtools::install_github("SNStatComp/rtrim/pkg")`

**Comment by lionel68** [comment]
Thanks @RetoSchmucki for your swift answer, it this repo: SNStatComp/rtrim, the official rtrim one? I.e. all future changes to the code will be pushed here?

**Comment by pwbogaart** [comment]
Hi;

Yes the package was autoremoved from CRAN because it’s not compatible with future R versions. I’m solving these right now and will re-submit to CRAN within a few days.
Hope this is quick enough?
Sorry for the inconvenience...
--
Met vriendelijke groet / Kind regards
Patrick Bogaart

**Comment by lionel68** [comment]
No worries, got it installed following @RetoSchmucki code. 
Just wanted to let you guys, and other users now ...
