### ISSUE TITLE
 TRIM for Python

### ISSUE THREAD

**Issue by AndranikUgujyan** [SNStatComp/rtrim#31]
Does [TRIM](https://www.cbs.nl/en-gb/society/nature-and-environment/indices-and-trends--trim--) available for Python, or there is materials that can help me to write TRIM for Python, because Python is better than R as it can be used for multiple purposes. It has better scalability, performance, integration, etc.

**Comment by pwbogaart** [comment]
You might try from the code and the methods report. But I don't think Python does a better job here.
