### ISSUE TITLE
RTRIM no longer on CRAN

### ISSUE THREAD

**Issue by jordri77** [SNStatComp/rtrim#32]
Hi folks,

RTRIM stopped working for me when updating to R 4.3.2 and in fact now appears to be on CRAN no longer. Aside from using archived versions are there any plans to publish a new RTRIM version any time soon?

**Comment by pwbogaart** [comment]
Oh! Thanks for warming me. Will fix it next week when I’m back from vacation.--Met vriendelijke groet / Kind regardsPatrick BogaartOp 7 mei 2024 om 00:52 heeft jordri77 ***@***.***> het volgende geschreven:﻿
Hi folks,
RTRIM stopped working for me when updating to R 4.3.2 and in fact now appears to be on CRAN no longer. Aside from using archived versions are there any plans to publish a new RTRIM version any time soon?

**Comment by pwbogaart** [comment]
It's back on CRAN (version 2.3.0)
